'use client'

import { useEffect, useState } from 'react'
import type { AssessmentLead, AssessmentLeadStatus, SafetyGradeLetter } from '../../../lib/types'

const statuses: AssessmentLeadStatus[] = ['submitted', 'qualified', 'scoped', 'invoiced', 'paid', 'in_review', 'factual_review', 'published', 'declined']

function ReportEditor({ lead, onSaved }: { lead: AssessmentLead; onSaved: () => void }) {
  const [form, setForm] = useState({ slug: `${lead.protocol}-${lead.pool}`.toLowerCase().replace(/[^a-z0-9]+/g, '-'), assessedAt: new Date().toISOString().slice(0, 10), methodologyVersion: 'v1.0', letter: 'B' as SafetyGradeLetter, score: '78', label: 'Safe', gradeSummary: '', weakest: 'APY stability', liquidity: '80', stability: '75', sustainability: '78', completeness: '90', strengths: '', watchpoints: '', summary: '' })
  const [message, setMessage] = useState('')
  function update(key: keyof typeof form, value: string) { setForm((current) => ({ ...current, [key]: value })) }
  async function submit(event: React.FormEvent) { event.preventDefault(); setMessage('Saving report for factual review...'); const response = await fetch('/api/ops/assessments', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ leadId: lead.id, slug: form.slug, protocol: lead.protocol, pool: lead.pool, chain: lead.chain, assessedAt: form.assessedAt, methodologyVersion: form.methodologyVersion, grade: { letter: form.letter, score: Number(form.score), label: form.label, summary: form.gradeSummary, weakest: form.weakest }, signals: { liquidity: Number(form.liquidity), stability: Number(form.stability), sustainability: Number(form.sustainability), completeness: Number(form.completeness) }, strengths: form.strengths.split('\n').map((item) => item.trim()).filter(Boolean), watchpoints: form.watchpoints.split('\n').map((item) => item.trim()).filter(Boolean), summary: form.summary }) }); const result = await response.json().catch(() => ({})); if (!response.ok) { setMessage(result.error || 'Could not save report.'); return } setMessage(`Saved. Factual review ends ${new Date(result.factualReviewDeadline).toLocaleDateString()}.`); onSaved() }
  return <details className="ql-ops-editor"><summary>Prepare report</summary><form className="ql-form-grid" onSubmit={submit}><label>Public slug<input required value={form.slug} onChange={(event) => update('slug', event.target.value)} /></label><label>Assessed date<input type="date" required value={form.assessedAt} onChange={(event) => update('assessedAt', event.target.value)} /></label><label>Grade<select value={form.letter} onChange={(event) => update('letter', event.target.value)}>{['A', 'B', 'C', 'D', 'F'].map((letter) => <option key={letter}>{letter}</option>)}</select></label><label>Score<input type="number" min="0" max="100" required value={form.score} onChange={(event) => update('score', event.target.value)} /></label><label>Grade label<input required value={form.label} onChange={(event) => update('label', event.target.value)} /></label><label>Weakest signal<input required value={form.weakest} onChange={(event) => update('weakest', event.target.value)} /></label><label>Liquidity<input type="number" min="0" max="100" required value={form.liquidity} onChange={(event) => update('liquidity', event.target.value)} /></label><label>APY stability<input type="number" min="0" max="100" required value={form.stability} onChange={(event) => update('stability', event.target.value)} /></label><label>Reward quality<input type="number" min="0" max="100" required value={form.sustainability} onChange={(event) => update('sustainability', event.target.value)} /></label><label>Data completeness<input type="number" min="0" max="100" required value={form.completeness} onChange={(event) => update('completeness', event.target.value)} /></label><label className="ql-form-span">Grade explanation<textarea required rows={2} value={form.gradeSummary} onChange={(event) => update('gradeSummary', event.target.value)} /></label><label>Strengths, one per line<textarea rows={3} value={form.strengths} onChange={(event) => update('strengths', event.target.value)} /></label><label>Watchpoints, one per line<textarea rows={3} value={form.watchpoints} onChange={(event) => update('watchpoints', event.target.value)} /></label><label className="ql-form-span">Public report summary<textarea required rows={3} value={form.summary} onChange={(event) => update('summary', event.target.value)} /></label><div className="ql-form-actions ql-form-span"><button type="submit" className="ql-btn ql-btn--primary">Save for factual review</button>{message ? <span role="status">{message}</span> : null}</div></form></details>
}

export default function AssessmentOpsPage() {
  const [leads, setLeads] = useState<AssessmentLead[]>([]); const [error, setError] = useState('')
  useEffect(() => { fetch('/api/ops/assessments').then(async (response) => { if (!response.ok) throw new Error('Owner access required'); const data = await response.json(); setLeads(data.leads) }).catch((reason) => setError(reason.message)) }, [])
  async function update(leadId: string, status: AssessmentLeadStatus) { const response = await fetch('/api/ops/assessments', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ leadId, status }) }); if (response.ok) setLeads((current) => current.map((lead) => lead.id === leadId ? { ...lead, status } : lead)) }
  return <main className="qy-analytics"><div className="qy-container"><div className="qy-analytics-head"><div><span className="qy-overline qy-overline-signal">Private operations</span><h1 className="qy-h2">Assessment queue</h1><p className="qy-analytics-sub">Qualify requests, scope the evidence, and prepare reports for factual review.</p></div></div>{error ? <p role="alert">{error}</p> : <div className="ql-ops-list">{leads.map((lead) => <article className="ql-ops-item" key={lead.id}><div><span className="ql-eyebrow">{lead.tier} · {new Date(lead.createdAt).toLocaleDateString()}</span><h2>{lead.protocol} · {lead.pool}</h2><p>{lead.requesterName} · {lead.workEmail} · {lead.chain}</p><p>{lead.notes || 'No notes provided.'}</p><ReportEditor lead={lead} onSaved={() => setLeads((current) => current.map((item) => item.id === lead.id ? { ...item, status: 'factual_review' } : item))} /></div><select value={lead.status} onChange={(event) => update(lead.id, event.target.value as AssessmentLeadStatus)}>{statuses.map((status) => <option key={status} value={status}>{status.replace('_', ' ')}</option>)}</select></article>)}</div>}</div></main>
}
