import type { Metadata, Viewport } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL
  ?? (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'https://quickyield.vercel.app')

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: 'QuickYield - DeFi Yield Radar',
  description:
    'QuickYield scans live DeFi yield pools with safety context, target rules, and Telegram alerts for non-custodial yield research.',
  icons: {
    icon: '/favicon.svg',
  },
  openGraph: {
    title: 'QuickYield - DeFi Yield Radar',
    description:
      'Scan DeFi yield pools, save targets, and get alerts when cleaner opportunities match your rules.',
    type: 'website',
    siteName: 'QuickYield',
    // Social card image is generated by app/opengraph-image.tsx (1200×630 PNG).
  },
  twitter: {
    card: 'summary_large_image',
    title: 'QuickYield - DeFi Yield Radar',
    description:
      'The Bloomberg Terminal for DeFi yield — scan live pools, grade their safety A–F, and get alerted before yields turn.',
  },
}

export const viewport: Viewport = {
  themeColor: '#f8f9fa',
  colorScheme: 'light',
}

const clerkAppearance = {
  variables: {
    colorPrimary: '#0066cc',
    colorBackground: '#ffffff',
    colorText: '#1a1d23',
    colorTextSecondary: '#626670',
    colorInputBackground: '#f8f9fa',
    colorInputText: '#1a1d23',
    colorNeutral: '#ffffff',
    borderRadius: '8px',
    fontFamily: 'var(--font-sans, ui-sans-serif, system-ui, sans-serif)',
  },
  elements: {
    card: { backgroundColor: '#ffffff', border: '1px solid rgba(0,0,0,0.08)', boxShadow: '0 1px 3px rgba(0,0,0,0.08)' },
    headerTitle: { color: '#1a1d23' },
    headerSubtitle: { color: '#626670' },
    socialButtonsBlockButton: { borderColor: 'rgba(0,0,0,0.12)' },
    formButtonPrimary: { backgroundColor: '#0066cc', color: '#ffffff', textTransform: 'none' as const, fontWeight: 600 },
    footerActionLink: { color: '#0066cc' },
  },
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider appearance={clerkAppearance}>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  )
}
