import type { Metadata, Viewport } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Instrument_Sans, JetBrains_Mono, Newsreader } from 'next/font/google'
import './globals.css'

/**
 * Fonts are loaded through next/font (self-hosted, preloaded, no layout shift).
 * A plain CSS `@import url(fonts.googleapis...)` does NOT survive the Turbopack
 * build — it gets stripped, and every family silently falls back.
 *
 * Newsreader (serif) = editorial surfaces: marketing headlines + articles.
 * Instrument Sans = UI/data surfaces. JetBrains Mono = tickers and figures.
 */
const fontSerif = Newsreader({
  subsets: ['latin'],
  display: 'swap',
  style: ['normal', 'italic'],
  variable: '--font-serif-src',
})
const fontSans = Instrument_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans-src',
})
const fontMono = JetBrains_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-mono-src',
})

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL
  ?? (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'https://quickyield.vercel.app')

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: 'QuickYield — Yield research you can audit, not just trust',
    template: '%s | QuickYield',
  },
  description:
    'QuickYield grades every live onchain yield pool A–F under a published methodology and commits every grade to a public, timestamped ledger. Non-custodial research and alerts.',
  icons: {
    icon: '/favicon.svg',
  },
  openGraph: {
    title: 'QuickYield — Yield research you can audit, not just trust',
    description:
      'Every pool graded A–F under a published methodology. Every grade committed to a public, timestamped ledger before the outcome is known.',
    type: 'website',
    siteName: 'QuickYield',
    // Social card image is generated by app/opengraph-image.tsx (1200×630 PNG).
  },
  twitter: {
    card: 'summary_large_image',
    title: 'QuickYield — Yield research you can audit, not just trust',
    description:
      'Every pool graded A–F under a published methodology. Every grade committed to a public, timestamped ledger before the outcome is known.',
  },
}

export const viewport: Viewport = {
  themeColor: '#07090d',
  colorScheme: 'dark',
}

const clerkAppearance = {
  variables: {
    colorPrimary: '#2f88ff',
    colorBackground: '#10151c',
    colorText: '#f5f6f8',
    colorTextSecondary: '#a6adba',
    colorInputBackground: '#0a0d12',
    colorInputText: '#f5f6f8',
    colorNeutral: '#f5f6f8',
    borderRadius: '10px',
    fontFamily: 'var(--font-sans, ui-sans-serif, system-ui, sans-serif)',
  },
  elements: {
    card: { backgroundColor: '#10151c', border: '1px solid rgba(255,255,255,0.08)', boxShadow: '0 16px 48px -16px rgba(0,0,0,0.55)' },
    headerTitle: { color: '#f5f6f8' },
    headerSubtitle: { color: '#a6adba' },
    socialButtonsBlockButton: { borderColor: 'rgba(255,255,255,0.12)' },
    formButtonPrimary: { backgroundColor: '#2f88ff', color: '#ffffff', textTransform: 'none' as const, fontWeight: 600 },
    footerActionLink: { color: '#2f88ff' },
  },
}

// Only mount Clerk when a real publishable key is configured. Without this,
// an absent/placeholder key drops Clerk into "keyless mode" (a full-page
// claim overlay + a client chunk that fails to load), which blanks local
// dev. Production sets a real pk_live/pk_test key, so Clerk mounts normally.
const clerkPublishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
const clerkEnabled = typeof clerkPublishableKey === 'string' && clerkPublishableKey.startsWith('pk_')

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const html = (
    <html lang="en" className={`${fontSerif.variable} ${fontSans.variable} ${fontMono.variable}`}>
      <body>{children}</body>
    </html>
  )
  if (!clerkEnabled) return html
  return <ClerkProvider appearance={clerkAppearance}>{html}</ClerkProvider>
}
