import type { Metadata, Viewport } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL
  ?? (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'https://quickyield.vercel.app')

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: 'QuickYield - DeFi Yield Radar',
  description:
    'QuickYield scans live DeFi yield pools with safety context, target rules, and Telegram alerts for non-custodial yield research.',
  icons: {
    icon: '/favicon.svg',
  },
  openGraph: {
    title: 'QuickYield - DeFi Yield Radar',
    description:
      'Scan DeFi yield pools, save targets, and get alerts when cleaner opportunities match your rules.',
    type: 'website',
    siteName: 'QuickYield',
    // Social card image is generated by app/opengraph-image.tsx (1200×630 PNG).
  },
  twitter: {
    card: 'summary_large_image',
    title: 'QuickYield - DeFi Yield Radar',
    description:
      'The Bloomberg Terminal for DeFi yield — scan live pools, grade their safety A–F, and get alerted before yields turn.',
  },
}

export const viewport: Viewport = {
  themeColor: '#0a0d14',
  colorScheme: 'dark',
}

const clerkAppearance = {
  variables: {
    colorPrimary: '#00d9ff',
    colorBackground: '#0f1419',
    colorText: '#e8e8e8',
    colorTextSecondary: '#8a9199',
    colorInputBackground: '#151c28',
    colorInputText: '#e8e8e8',
    colorNeutral: '#0f1419',
    borderRadius: '8px',
    fontFamily: 'var(--font-sans, ui-sans-serif, system-ui, sans-serif)',
  },
  elements: {
    card: { backgroundColor: '#0f1419', border: '1px solid rgba(255,255,255,0.08)', boxShadow: '0 0 32px rgba(0,217,255,0.15)' },
    headerTitle: { color: '#e8e8e8' },
    headerSubtitle: { color: '#8a9199' },
    socialButtonsBlockButton: { borderColor: 'rgba(255,255,255,0.12)' },
    formButtonPrimary: { backgroundColor: '#00d9ff', color: '#0a0d14', textTransform: 'none' as const, fontWeight: 700 },
    footerActionLink: { color: '#00d9ff' },
  },
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider appearance={clerkAppearance}>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  )
}
