import type { Opportunity } from './types'

const now = new Date().toISOString()

export const curatedOpportunities: Opportunity[] = [
  {
    id: 'curated-aave-usdc-base',
    rank: 2,
    name: 'USDC lending vault',
    platform: 'Aave',
    category: 'Stablecoin lending',
    chain: 'Base',
    asset: 'USDC',
    symbol: 'USDC',
    apy: 8.4,
    trend: 'up',
    trendValue: 0.8,
    risk: 'Low',
    minimum: 25,
    time: '5 min',
    tvl: '$146M',
    tvlUsd: 146_000_000,
    gas: '$0.08',
    confidence: 91,
    dailyLow: 0.02,
    dailyHigh: 0.04,
    action: 'Review lending market',
    actionUrl: 'https://app.aave.com/',
    source: 'Curated',
    notes: 'Blue-chip lending market, low gas, no lockup. APY can move quickly when utilization changes.',
    flags: ['TVL above $100M', 'No lockup', 'Stablecoin exposure'],
    lastSeenAt: now,
  },
  {
    id: 'curated-jito-sol',
    rank: 1,
    name: 'SOL liquid staking',
    platform: 'Jito',
    category: 'Staking',
    chain: 'Solana',
    asset: 'SOL',
    symbol: 'SOL',
    apy: 7.1,
    trend: 'up',
    trendValue: 0.3,
    risk: 'Low',
    minimum: 10,
    time: '5 min',
    tvl: '$1.7B',
    tvlUsd: 1_700_000_000,
    gas: '<$0.01',
    confidence: 94,
    dailyLow: 0.01,
    dailyHigh: 0.03,
    action: 'Compare staking routes',
    actionUrl: 'https://www.jito.network/staking/',
    source: 'Curated',
    notes: 'Simple staking route with deep liquidity. Token price movement matters more than yield.',
    flags: ['Very low fees', 'Large TVL', 'Liquid staking token'],
    lastSeenAt: now,
  },
  {
    id: 'curated-lido-eth-arbitrum',
    rank: 3,
    name: 'ETH L2 staking route',
    platform: 'Lido',
    category: 'Staking',
    chain: 'Arbitrum',
    asset: 'ETH',
    symbol: 'ETH',
    apy: 3.9,
    trend: 'flat',
    trendValue: 0.1,
    risk: 'Low',
    minimum: 50,
    time: '15 min',
    tvl: '$35B',
    tvlUsd: 35_000_000_000,
    gas: '$0.21',
    confidence: 89,
    dailyLow: 0.01,
    dailyHigh: 0.02,
    action: 'Open staking option',
    actionUrl: 'https://lido.fi/',
    source: 'Curated',
    notes: 'Lower headline APY, but strong protocol history and easier beginner explanation.',
    flags: ['Established protocol', 'Bridge awareness needed', 'Low APY volatility'],
    lastSeenAt: now,
  },
  {
    id: 'curated-coinbase-learn',
    rank: 4,
    name: 'Beginner learn reward',
    platform: 'Coinbase',
    category: 'Learn and earn',
    chain: 'Exchange',
    asset: 'VAR',
    symbol: 'LEARN',
    apy: 0,
    trend: 'up',
    trendValue: 2.4,
    risk: 'Low',
    minimum: 0,
    time: '15 min',
    tvl: 'N/A',
    tvlUsd: 0,
    gas: '$0',
    confidence: 86,
    dailyLow: 1,
    dailyHigh: 6,
    action: 'Check available lessons',
    actionUrl: 'https://www.coinbase.com/earn',
    source: 'Curated',
    notes: 'Availability changes by region and account status. Best displayed as a task, not an APY.',
    flags: ['No capital needed', 'Account required', 'Region dependent'],
    lastSeenAt: now,
  },
  {
    id: 'curated-binance-usdt',
    rank: 5,
    name: 'USDT flexible earn',
    platform: 'Binance Earn',
    category: 'Exchange earn',
    chain: 'Exchange',
    asset: 'USDT',
    symbol: 'USDT',
    apy: 5.3,
    trend: 'down',
    trendValue: 0.5,
    risk: 'Medium',
    minimum: 10,
    time: '5 min',
    tvl: 'N/A',
    tvlUsd: 0,
    gas: '$0',
    confidence: 78,
    dailyLow: 0.01,
    dailyHigh: 0.03,
    action: 'Open exchange earn',
    actionUrl: 'https://www.binance.com/en/earn',
    source: 'Curated',
    notes: 'Easy setup, but exchange custody risk should be made obvious for beginners.',
    flags: ['Custody risk', 'Flexible terms', 'No network fee'],
    lastSeenAt: now,
  },
  {
    id: 'curated-layer3-base',
    rank: 6,
    name: 'Base ecosystem task',
    platform: 'Layer3',
    category: 'Airdrop task',
    chain: 'Base',
    asset: 'ETH',
    symbol: 'BASE',
    apy: 0,
    trend: 'flat',
    trendValue: 0,
    risk: 'Medium',
    minimum: 15,
    time: '15 min',
    tvl: 'N/A',
    tvlUsd: 0,
    gas: '$0.15',
    confidence: 73,
    dailyLow: 0,
    dailyHigh: 4,
    action: 'View task checklist',
    actionUrl: 'https://app.layer3.xyz/category/base',
    source: 'Curated',
    notes: 'Speculative reward only. Show as optional learning activity, never guaranteed income.',
    flags: ['Speculative reward', 'Low gas', 'Wallet activity needed'],
    lastSeenAt: now,
  },
]
